services:
  postgres:
    image: postgres:16-alpine
    container_name: viverosmart-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: viverosmart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: micontaseña
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: viverosmart-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:micontaseña@postgres:5432/viverosmart?schema=public"
      JWT_SECRET: "screto no èsto"
      FRONTEND_URL: "http://localhost"
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: viverosmart-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data: