apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: viverosmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/viverosmart-api:IMAGE_TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: FRONTEND_URL
              value: https://app.TU_DOMINIO
          envFrom:
            - secretRef:
                name: api-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: viverosmart
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 5000
